### ISSUE TITLE
Calling depends_on macOS: "10.1" is deprecated and will be disabled on 2019-10-15!

### ISSUE THREAD

**Issue by Signify** [sticklerm3/homebrew-pourhouse#49]
I am getting this error: Calling depends_on macOS: "10.1" is deprecated and will be disabled on 2019-10-15! Use depends_on el_capitan instead in the following files on line 10:

bailiff.rb.10
cirrus.rb:10
precize.rb:10
revisionist.rb:10
scrub.rb:10

When will a fix be available?

Amanda Mays

**Comment by sticklerm3** [comment]
Hey! sorry for the delayed response! I haven't been on this much! I *should* have all the formulas fixed and (mostly) updated! If theres anything I may have missed just let me know!

**Comment by sticklerm3** [comment]
#62 - bailiff
#57 - cirrus
#58 - precize 
#59 - revisionist 
#61 - scrub
